apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
spec:
  type: ClusterIP
  clusterIP: 10.109.221.98
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: web
